services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: claimix
      TZ: 'UTC'
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgresql/common/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
      - ./healthchecks:/healthchecks:ro
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    healthcheck:
      test: ["CMD-SHELL", "/healthchecks/postgres.sh"]
      interval: 30s
      timeout: 30s
      retries: 5
    networks:
      - infra
  liquibase_claimix_postgres:
    image: liquibase/liquibase:4.19
    container_name: liquibase-claimix-postgres
    environment:
      LIQUIBASE_COMMAND_URL: "jdbc:postgresql://postgres:5432/claimix?currentSchema=claimix"
      LIQUIBASE_COMMAND_USERNAME: postgres
      LIQUIBASE_COMMAND_PASSWORD: postgres
      LIQUIBASE_COMMAND_CHANGELOG_FILE: dbchangelog.yml
      LIQUIBASE_COMMAND_DEFAULT_SCHEMA_NAME: claimix
      SCHEMA: claimix
      LIQUIBASE_LIQUIBASE_SCHEMA_NAME: claimix
    volumes:
      - ../db/liquibase/:/dbobjects:ro
    command: "--classpath=/dbobjects --search-path=/dbobjects/claimix \
      --defaultsFile=/dbobjects/claimix/liquibase.properties update"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - infra

networks:
  infra:
    external: true

volumes:
  postgres-data:
